### ISSUE TITLE
Super slow

### ISSUE THREAD

**Issue by albinahlback** [cross-platform-actions/freebsd-builder#1]
We have CI for our library, and FreeBSD takes at least 20 times longer to finish compared to native Ubuntu. What can I do in order to speed up this process?

**Comment by jacob-carlborg** [comment]
I need a bit more context. Can you link to a job that shows the problem?

**Comment by albinahlback** [comment]
Have a look at our CI at https://github.com/flintlib/flint2/actions/runs/4456039991. Basically we compile our library and check it via our test files written in C. We use a very low test multiplier for FreeBSD, but yet its way slower than Ubuntu for example. Even Cygwin is faster.

**Comment by albinahlback** [comment]
Here is one that did not time out: https://github.com/flintlib/flint2/actions/runs/4369437605/jobs/7643228615

**Comment by jacob-carlborg** [comment]
It's slow because you're using Linux runners. The Linux runners don't support hardware accelerated nested virtualization. Please try using a macOS runner. It does support support hardware accelerated nested virtualization.

**Comment by albinahlback** [comment]
Oh, thanks a lot!
