### ISSUE TITLE
Ubuntu 22.10 is end of life

### ISSUE THREAD

**Issue by yorickpeterse** [cross-platform-actions/freebsd-builder#4]
The CI job used to build the image uses the 22.10 version of Ubuntu, which is end of life (https://fridge.ubuntu.com/2023/06/14/ubuntu-22-10-kinetic-kudu-reaches-end-of-life-on-july-20-2023/). It seems this results in `apt update` failing, as seen in https://github.com/inko-lang/freebsd-builder/actions/runs/6436773502/job/17480859221. 

My workaround is to use `ubuntu:latest` instead, but this should probably be incorporated into this repository as well. If that's OK I'd be happy to set up a pull request for it :smile:

**Comment by yorickpeterse** [comment]
To add to that: given the container version is the same as the host Ubuntu runner (I think at least), it begs the question if the container is actually necessary in the first place. Perhaps it's easier to just run on the runner directly?

**Comment by jacob-carlborg** [comment]
The runner is already `ubuntu:latest`:

https://github.com/cross-platform-actions/freebsd-builder/blob/9f26973f4308fbf852026b30d27eedc422149703/.github/workflows/build.yml#L14

But I guess the container needs to be updated.

GitHub has a tendency to break the runners, like removing packages/libraries. This happened recently [1]. By running inside a container we're in more control of what packages and libraries are available and hopefully mitigate that issue.

[1] https://github.com/cross-platform-actions/action/issues/62#issuecomment-1740947035

**Comment by yorickpeterse** [comment]
@jacob-carlborg Ah gotcha. The fix I applied [was to just use ubuntu:latest for the container](https://github.com/inko-lang/freebsd-builder/commit/cb0b81455bacd345b6910c762f4642e8d03e1cd0). That seems to work fine, though using a fixed LTS version may be better for stability/consistency.
